spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${properties.mail.username}
    password: ${properties.mail.password}
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls:
            enable: true

custom:
  mail:
    change-password-redirect-url: ${properties.mail.change-password-redirect-url}